import { useI18n } from "../../lib/i18n";
import { Page } from "./Layout";

export default function Legal({ kind }) {
  const { t, lang } = useI18n();
  const contact = import.meta.env.VITE_CONTACT_EMAIL;
  const updated = "2026-10-07";
  const privacy = [
    [t("Kimiz", "Who we are"), t("Loss (loss.tr), link kısaltma, QR kod ve analiz hizmeti sunar. Bu metin, hizmeti kullanırken hangi verilerin neden işlendiğini açıklar.", "Loss (loss.tr) provides link shortening, QR codes and analytics. This text explains what data is processed and why.")],
    [t("Hesap verileri", "Account data"), t("Hesap oluştururken e-posta adresi, ad (isteğe bağlı) ve kimlik doğrulama sağlayıcısı tarafından üretilen kullanıcı kimliği işlenir. Hukuki sebep: sözleşmenin ifası.", "When you create an account we process your email address, optional name and the user ID generated by the authentication provider. Legal basis: performance of the contract.")],
    [t("Bağlantı verileri", "Link data"), t("Oluşturduğunuz bağlantılar, hedef adresler, etiketler ve ayarlar hesabınıza bağlı olarak saklanır. Parolalar tek yönlü olarak (scrypt) özetlenir; düz metin saklanmaz.", "The links, destinations, tags and settings you create are stored against your account. Passwords are stored as one-way scrypt hashes, never in plain text.")],
    [t("Ziyaretçi analizi", "Visitor analytics"), t("Kısa bağlantıyı açan ziyaretçiler için çerez kullanılmaz ve IP adresi saklanmaz. Her tıklama için ülke, (varsa) şehir, cihaz türü, tarayıcı, işletim sistemi, yönlendiren site, dil ve günlük değişen tuzla üretilmiş tek yönlü bir özet kaydedilir. Bu özet, aynı günde tekrar eden ziyaretleri saymak içindir; günler arasında kişi eşleştirmeye elverişli değildir. Hukuki sebep: meşru menfaat (hizmet sahiplerine toplu istatistik sağlamak).", "For people opening a short link no cookies are used and no IP address is stored. For each click we record country, city (if available), device type, browser, operating system, referrer, language and a one-way hash made with a salt that changes daily. The hash only lets us count repeat visits within a day; it cannot be used to follow a person across days. Legal basis: legitimate interest (providing aggregate statistics to link owners).")],
    [t("Ödemeler", "Payments"), t("Ödemeler PayTR tarafından işlenir; kart bilgileriniz Loss sunucularına ulaşmaz. Sipariş kaydı (plan, tutar, durum) muhasebe yükümlülükleri için saklanır.", "Payments are processed by PayTR; card details never reach Loss servers. Order records (plan, amount, status) are kept for accounting obligations.")],
    [t("Hizmet sağlayıcılar", "Processors"), t("Verileri barındırmak ve kimlik doğrulamak için Google Firebase / Google Cloud, uygulamayı sunmak için Vercel kullanılır. İsteğe bağlı olarak zararlı adres taraması için Google Web Risk kullanılabilir (yalnızca hedef URL gönderilir).", "We use Google Firebase / Google Cloud for hosting data and authentication, and Vercel to serve the application. Google Web Risk may optionally be used to scan destination URLs (only the destination URL is sent).")],
    [t("Saklama ve silme", "Retention & deletion"), t("Verileriniz hesabınız açık olduğu sürece saklanır. Ayarlar → Verileriniz bölümünden verilerinizi indirebilir veya hesabınızı kalıcı olarak silebilirsiniz; silme bağlantıları, tıklama geçmişini ve anahtarları kaldırır.", "Your data is kept while your account is open. Under Settings → Your data you can download your data or permanently delete your account; deletion removes links, click history and keys.")],
    [t("Haklarınız (KVKK / GDPR)", "Your rights (KVKK / GDPR)"), t("Erişim, düzeltme, silme, taşıma ve itiraz haklarına sahipsiniz. Çoğunu panelden kendiniz kullanabilirsiniz; diğer talepler için bize yazın.", "You have the rights of access, rectification, erasure, portability and objection. You can exercise most of them yourself in the dashboard; write to us for anything else.")],
    [t("İletişim", "Contact"), contact ? t("Gizlilikle ilgili talepler: ", "Privacy requests: ") + contact : t("İletişim bilgileri hesabınızdaki ayarlarda ve destek kanallarında yayımlanır.", "Contact details are published in your account settings and support channels.")],
  ];
  const terms = [
    [t("Hizmet", "The service"), t("Loss, bağlantı kısaltma, QR kod üretimi ve analiz araçları sunar. Hizmeti bu koşulları kabul ederek kullanırsınız.", "Loss provides link shortening, QR code generation and analytics tools. By using the service you accept these terms.")],
    [t("Kabul edilebilir kullanım", "Acceptable use"), t("Kimlik avı, dolandırıcılık, zararlı yazılım, spam, yasa dışı veya haklara aykırı içeriğe yönlendiren bağlantılar oluşturamazsınız. Hizmeti aşırı yükleyecek otomasyon, bağlantıları gizleyerek yanıltma amacıyla kullanım ve diğer kısaltıcılara zincirleme yönlendirme yasaktır.", "You may not create links that lead to phishing, fraud, malware, spam, or illegal or infringing content. Automation that overloads the service, using links to mislead by concealment, and chaining to other shorteners are prohibited.")],
    [t("Moderasyon", "Moderation"), t("İhlal bildirimleri incelenir. Bağlantıları önceden haber vermeden devre dışı bırakma ve ihlal eden hesapları askıya alma hakkımız saklıdır.", "Abuse reports are reviewed. We may disable links without notice and suspend violating accounts.")],
    [t("Planlar ve ödeme", "Plans & payment"), t("Ücretli planlar seçilen dönem için peşin tahsil edilir ve her dönem otomatik yenilenir. Aboneliği panelden istediğiniz zaman iptal edebilirsiniz; erişiminiz ödenen dönemin sonuna kadar sürer. Fiyatlar KDV hariç TL cinsindendir.", "Paid plans are charged in advance for the chosen period and renew automatically. You can cancel at any time in the dashboard; access continues until the end of the paid period. Prices are in TRY excluding VAT.")],
    [t("Hizmet düzeyi", "Availability"), t("Hizmeti özenle sunarız ancak kesintisiz çalışma garanti edilmez. Planlı bakım ve beklenmeyen kesintiler olabilir.", "We operate the service with care but do not guarantee uninterrupted operation. Maintenance and unexpected outages may occur.")],
    [t("Sorumluluk", "Liability"), t("Bağlantı hedeflerinin içeriğinden bağlantıyı oluşturan sorumludur. Yasaların izin verdiği ölçüde, dolaylı zararlardan sorumluluğumuz hariç tutulur.", "The person who creates a link is responsible for the content of its destination. To the extent permitted by law, we exclude liability for indirect damages.")],
    [t("Değişiklikler", "Changes"), t("Bu koşulları güncelleyebiliriz; önemli değişiklikler uygulamada duyurulur.", "We may update these terms; material changes will be announced in the app.")],
  ];
  const sections = kind === "privacy" ? privacy : terms;
  return (
    <Page narrow>
      <article className="docs" style={{ padding: "56px 0 80px" }}>
        <h1>{kind === "privacy" ? t("Gizlilik politikası", "Privacy policy") : t("Kullanım koşulları", "Terms of service")}</h1>
        <p className="muted">{t("Son güncelleme", "Last updated")}: {updated}</p>
        {sections.map(([h, p]) => <section key={h}><h2>{h}</h2><p>{p}</p></section>)}
      </article>
    </Page>
  );
}
