export const TIERS = {
  free: {
    id: "free",
    name: "Başlangıç",
    badge: "Free",
    priceMonthly: 0,
    priceAnnual: 0,
    maxLinks: 50,
    maxClicks: 2500,
    domains: 0,
    description: "Bireysel kullanım, deneme ve temel link kısaltma için ideal.",
    features: [
      "50 Adet Kısa Link",
      "2,500 Aylık Tıklama",
      "Standart Vektörel QR Kodlar",
      "30 Günlük Temel Analitik",
      "Topluluk Desteği",
    ],
    disabled: [
      "Özel Markalı Domain (link.sirketiniz.com)",
      "Şifre & Tarih Korumalı Linkler",
      "Canlı UTM Kampanya Oluşturucu",
    ],
  },
  pro: {
    id: "pro",
    name: "Growth Pro",
    badge: "Popüler",
    priceMonthly: 19,
    priceAnnual: 180,
    maxLinks: 1500,
    maxClicks: 100000,
    domains: 3,
    description: "Büyüyen ekipler, pazarlamacılar ve ajanslar için gelişmiş araçlar.",
    features: [
      "1,500 Adet Kısa Link",
      "100,000 Aylık Tıklama Kapasitesi",
      "3 Özel Alan Adı (Custom Domain)",
      "Şifre & Son Kullanma Tarihi Koruması",
      "Gelişmiş UTM Kampanya Builder",
      "SVG & PNG QR Kod Stüdyosu",
      "1 Yıllık Detaylı Analitik Geçmişi",
      "Öncelikli E-posta Desteği",
    ],
    disabled: [
      "Kurumsal 99.9% SLA Garantisi",
      "Özel Hesap Yöneticisi",
    ],
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    badge: "Kurumsal",
    priceMonthly: 59,
    priceAnnual: 580,
    maxLinks: 50000,
    maxClicks: 2500000,
    domains: 25,
    description: "Yüksek hacimli trafik ve kurumsal güvenlik gerektiren işletmeler.",
    features: [
      "50,000 Bağlantı & 2.5M+ Tıklama",
      "25 Özel Markalı Alan Adı",
      "Gelişmiş Webhook Bildirimleri",
      "Kurumsal 99.9% Kesintisiz SLA",
      "SSO & Ekip Yetkilendirme",
      "7/24 Öncelikli Mühendis Desteği",
    ],
    disabled: [],
  },
};
