export const TIERS = {
  free: {
    id: "free",
    name: "Başlangıç (Free)",
    badge: "Ücretsiz",
    priceMonthly: 0,
    priceAnnual: 0,
    currency: "₺",
    maxLinks: 25, // Active Links Capacity
    maxClicks: 1000,
    fairUseRedirects: 10000,
    domains: 0,
    description: "Bireysel kullanım, test ve temel link kısaltma için ideal.",
    features: [
      "25 Adet Aktif Link Kapasitesi",
      "1,000 Aylık Analitik Tıklaması",
      "10,000 / ay Adil Kullanım Yönlendirmesi",
      "Standart Vektörel QR Kodlar",
      "30 Günlük Gizlilik Odaklı Analitik",
    ],
    disabled: [
      "Canlı Hedef URL Düzenleme",
      "Özel Markalı Alan Adı (Custom Domain)",
      "Şifre & Tarih Koruması",
      "Ekip Paylaşımı",
    ],
  },
  starter: {
    id: "starter",
    name: "Starter",
    badge: "Girişimci",
    priceMonthly: 399,
    priceAnnual: 3990,
    currency: "₺",
    maxLinks: 500, // Active Links Capacity
    maxClicks: 50000,
    fairUseRedirects: "Sınırsız",
    domains: 1,
    description: "İçerik üreticileri, butik markalar ve bağımsız profesyoneller için.",
    features: [
      "500 Adet Aktif Link Kapasitesi",
      "Sınırsız Ticari Yönlendirme Trafiği",
      "1 Özel Markalı Domain (link.markaniz.com)",
      "Canlı Hedef URL Düzenleme (QR Sabit Kalır)",
      "300 DPI Ultra HD PNG & SVG QR Stüdyosu",
      "UTM Kampanya Oluşturucu & Şablonlar",
      "1 Yıllık Detaylı Analitik Geçmişi",
    ],
    disabled: [
      "Şifre & Tarih Korumalı Linkler",
      "Çoklu Ekip Rolleri & Çalışma Alanı",
    ],
  },
  pro: {
    id: "pro",
    name: "Pro Team",
    badge: "Popüler",
    priceMonthly: 899,
    priceAnnual: 8990,
    currency: "₺",
    maxLinks: 2500, // Active Links Capacity
    maxClicks: 250000,
    fairUseRedirects: "Sınırsız",
    domains: 3,
    description: "Büyüyen şirketler, pazarlama ekipleri ve e-ticaret markaları için.",
    features: [
      "2,500 Adet Aktif Link Kapasitesi",
      "3 Özel Markalı Domain",
      "Şifre & Son Kullanma Tarihi Koruması",
      "Ekip Çalışma Alanı (5 Kullanıcı)",
      "300 DPI Vektörel QR Kod İndirme",
      "Gelişmiş Coğrafi & Cihaz Analitiği",
      "Öncelikli E-posta & Chat Desteği",
    ],
    disabled: [
      "Özel SLA Garantisi & Tahsisli IP",
    ],
  },
  agency: {
    id: "agency",
    name: "Agency / Scale",
    badge: "Kurumsal",
    priceMonthly: 2499,
    priceAnnual: 24990,
    currency: "₺",
    maxLinks: 15000, // Active Links Capacity
    maxClicks: 1500000,
    fairUseRedirects: "Sınırsız",
    domains: 15,
    description: "Ajanslar, holdingler ve kurumsal yüksek hacimli link operasyonları.",
    features: [
      "15,000 Adet Aktif Link Kapasitesi",
      "15 Özel Markalı Domain",
      "Sınırsız Ekip Üyesi & Rol Yönetimi",
      "Gelişmiş Webhook & REST API Erişimi",
      "99.9% Kesintisiz Çalışma SLA Garantisi",
      "PayTR Kurumsal Fatura Entegrasyonu",
      "Özel Müşteri Başarı Yöneticisi",
    ],
    disabled: [],
  },
};
