export const INITIAL_DEMO_LINKS = [
  {
    id: "go.consolaktif.com.tr__yaz-kampanyasi",
    domain: "go.consolaktif.com.tr",
    slug: "yaz-kampanyasi",
    title: "Yaz İndirimi 2026 Açılış Kampanyası",
    destination: "https://consolaktif.com.tr/kampanyalar/yaz-sezonu?utm_source=instagram&utm_medium=bio",
    shortUrl: "https://go.consolaktif.com.tr/yaz-kampanyasi",
    status: "active",
    clickCount: 1428,
    tag: "Pazarlama",
    password: "",
    expiresAt: "2026-09-30",
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 4 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 3600 * 2 },
  },
  {
    id: "go.consolaktif.com.tr__yeni-urun-lansmani",
    domain: "go.consolaktif.com.tr",
    slug: "yeni-urun-lansmani",
    title: "Akıllı Asistan v3.0 Lansman Sayfası",
    destination: "https://consolaktif.com.tr/urunler/akilli-asistan-v3",
    shortUrl: "https://go.consolaktif.com.tr/yeni-urun-lansmani",
    status: "active",
    clickCount: 892,
    tag: "Lansman",
    password: "",
    expiresAt: "",
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 9 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 3600 * 12 },
  },
  {
    id: "go.consolaktif.com.tr__yatirimci-sunumu",
    domain: "go.consolaktif.com.tr",
    slug: "yatirimci-sunumu",
    title: "Q3 Yatırımcı Bilgilendirme Raporu & Sunumu",
    destination: "https://consolaktif.com.tr/yatirimci/2026-q3-raporu.pdf",
    shortUrl: "https://go.consolaktif.com.tr/yatirimci-sunumu",
    status: "active",
    clickCount: 341,
    tag: "Kurumsal",
    password: "••••••••",
    expiresAt: "2026-12-31",
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 15 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 2 },
  },
  {
    id: "go.consolaktif.com.tr__newsletter-eylul",
    domain: "go.consolaktif.com.tr",
    slug: "newsletter-eylul",
    title: "Eylül 2026 Geliştirici Bülteni Özel Sayısı",
    destination: "https://consolaktif.com.tr/bulten/sayi-42",
    shortUrl: "https://go.consolaktif.com.tr/newsletter-eylul",
    status: "paused",
    clickCount: 673,
    tag: "E-bülten",
    password: "",
    expiresAt: "",
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 22 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 5 },
  },
  {
    id: "go.consolaktif.com.tr__discord-toplulugu",
    domain: "go.consolaktif.com.tr",
    slug: "discord-toplulugu",
    title: "ConsolAktif Yazılımcı Topluluğu Davet Linki",
    destination: "https://discord.gg/consolaktif-devs",
    shortUrl: "https://go.consolaktif.com.tr/discord-toplulugu",
    status: "active",
    clickCount: 2150,
    tag: "Topluluk",
    password: "",
    expiresAt: "",
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 45 },
    updatedAt: { seconds: Math.floor(Date.now() / 1000) - 86400 * 1 },
  },
];

export const MOCK_ANALYTICS = {
  totalClicks: 5484,
  uniqueVisitors: 4120,
  averageConversionRate: "4.8%",
  devices: [
    { label: "Mobil (iOS / Android)", percentage: 58, count: 3180, color: "#2563eb" },
    { label: "Masaüstü (Mac / Windows)", percentage: 37, count: 2029, color: "#10b981" },
    { label: "Tablet & Diğer", percentage: 5, count: 275, color: "#f59e0b" },
  ],
  countries: [
    { country: "Türkiye", flag: "🇹🇷", clicks: 3840, share: "70.0%" },
    { country: "Almanya", flag: "🇩🇪", clicks: 610, share: "11.1%" },
    { country: "Birleşik Krallık", flag: "🇬🇧", clicks: 340, share: "6.2%" },
    { country: "Amerika Birleşik Devletleri", flag: "🇺🇸", clicks: 290, share: "5.3%" },
    { country: "Hollanda", flag: "🇳🇱", clicks: 180, share: "3.3%" },
    { country: "Diğer Ülkeler", flag: "🌐", clicks: 224, share: "4.1%" },
  ],
  referrers: [
    { source: "Doğrudan / Doğrudan Giriş", count: 2140, share: "39%" },
    { source: "Instagram (Bio & Stories)", count: 1650, share: "30%" },
    { source: "X / Twitter", count: 870, share: "16%" },
    { source: "Google Arama", count: 520, share: "9%" },
    { source: "LinkedIn", count: 304, share: "6%" },
  ],
  weeklyClicks: [
    { day: "Pzt", clicks: 420 },
    { day: "Sal", clicks: 680 },
    { day: "Çar", clicks: 890 },
    { day: "Per", clicks: 810 },
    { day: "Cum", clicks: 1150 },
    { day: "Cts", clicks: 790 },
    { day: "Paz", clicks: 744 },
  ],
};
